import React from 'react';
import {connect} from 'react-redux';
import {listMainBranch} from '../../redux/actions/branchActions';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Header from '../../components/header';
import MainBranchDisplay from '../../components/mainBranchView';
import Footer from '../../components/footer';

class Home extends React.Component{
  
  constructor(props) {
    super(props);

    this.state = {};
  }

  componentDidMount() {
    this.props.listMainBranch(this.props.userId);
  }

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>GitoDo</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
  
        <Header></Header>
  
        <main className={styles.main + ' bg-gray-100 relative'}>
          <div className='sm:top-28 top-24 lg:right-7 right-2 lg:left-80 left-20 px-10 absolute w-auto'>
            <div className='container flex flex-row mx-auto items-center'>
              <h1 className='text-2xl font-semibold'>Branch</h1>
            </div>
          </div>
          <MainBranchDisplay mainLine={this.props.mainLine}></MainBranchDisplay>
        </main>
  
        <Footer></Footer>
      </div>
    );
  }
}

const mapStateToProps = state => ({
  userId: state.login.userId,
  mainLine: state.branch.mainLine,
  branchLoading: state.branch.branchLoading,
});

const mapDispatchToProps = {
  listMainBranch: listMainBranch,
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
