// Display page for single branch and edit

import { useRouter } from 'next/router'
import Head from 'next/head';
import styles from '../../../styles/Home.module.css';
import Header from '../../../components/header';
import EditTaskView from '../../../components/editTaskView';
import Footer from '../../../components/footer';
import { ListGroup, ListGroupItem } from 'reactstrap';

export default function Home() {
  const router = useRouter()
  const { title/*, id */} = router.query
  let c = {
    id:  90910,
    is_main: true,
    is_head: false,
    color: '#ffc107',
    mother_line_id: 1933, /* Main */
    create_date: '2021-05-30 07:45 Sun',
    due_date: '2021-06-29 06:33 Tue',
    title: 'Run 10 miles',
    url: 'https://google.com',
    importance: 2,
    content: 'Run for ten miles, and we can achieve our goal. \
    Loren LorenLorenLorenLorenLorenLorenLorenLorenLoren\
    LorenLorenLorenLorenLorenLorenLorenLoren.',
    achieved: false,
    achieved_at: null,
    subtask: [
      {'task': 'Milk', 'done': false, 'id': 1},
      {'task': 'Water', 'done': true, 'id': 2},
      {'task': 'Glass mug', 'done': false, 'id': 3}
    ]
  }
  let task = [c]

  let children = (
    <ListGroupItem className='empty d-flex justify-content-center align-items-center'>
      <div></div>
    </ListGroupItem>
  );
  if (task.length) {
    children = task.map((p) => (
      <ListGroupItem key={p.id} action>
        <EditTaskView {...p} />
      </ListGroupItem>
    ));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Edit Task {title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header></Header>

      <main className={styles.main + ' bg-gray-100'}>
        <ListGroup>
            {children}
        </ListGroup>
      </main>

      <Footer></Footer>
    </div>
  );
}