import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import MainTaskView from '../components/mainTaskView';
import Footer from '../components/footer';
import BranchCanvas from '../components/branchCanvas';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GitoDo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header></Header>

      <main className={styles.main + ' bg-gray-100 relative'}>
        <BranchCanvas ></BranchCanvas>
        <div className='sm:top-28 top-24 lg:right-7 right-2 lg:left-80 left-20 px-10 absolute w-auto'>
          <div className='flex flex-row mx-auto items-center'>
            <h1 className='text-2xl font-semibold'>Task</h1>
            <div className='flex-grow' />
          </div>
        </div>
        <MainTaskView></MainTaskView>
      </main>

      <Footer></Footer>
    </div>
  );
}
