// Display page for single branch and edit

import { useRouter } from 'next/router'
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Header from '../../components/header';
import EditBranchView from '../../components/editBranchView';
import Footer from '../../components/footer';

export default function Home() {
  const router = useRouter()
  const { branchName/*, id */} = router.query

  return (
    <div className={styles.container}>
      <Head>
        <title>Edit {branchName}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header></Header>

      <main className={styles.main + ' bg-gray-100'}>
        <EditBranchView></EditBranchView>
      </main>

      <Footer></Footer>
    </div>
  );
}